[2021-01-21 23:22:55,263] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_3 2021-01-21T23:22:53.765633+00:00 [queued]>
[2021-01-21 23:22:55,282] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_3 2021-01-21T23:22:53.765633+00:00 [queued]>
[2021-01-21 23:22:55,282] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-21 23:22:55,282] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-21 23:22:55,282] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-21 23:22:55,290] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): task_3> on 2021-01-21T23:22:53.765633+00:00
[2021-01-21 23:22:55,293] {standard_task_runner.py:51} INFO - Started process 594516 to run task
[2021-01-21 23:22:55,298] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_rule', 'task_3', '2021-01-21T23:22:53.765633+00:00', '--job-id', '107', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule.py', '--cfg-path', '/tmp/tmpk26xeb8d']
[2021-01-21 23:22:55,299] {standard_task_runner.py:76} INFO - Job 107: Subtask task_3
[2021-01-21 23:22:55,355] {logging_mixin.py:103} INFO - Running <TaskInstance: trigger_rule.task_3 2021-01-21T23:22:53.765633+00:00 [running]> on host ip-172-31-18-6.ap-south-1.compute.internal
[2021-01-21 23:22:55,405] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trigger_rule
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2021-01-21T23:22:53.765633+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-01-21T23:22:53.765633+00:00
[2021-01-21 23:22:55,405] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-01-21 23:22:55,406] {bash.py:158} INFO - Running command: exit 0
[2021-01-21 23:22:55,413] {bash.py:169} INFO - Output:
[2021-01-21 23:22:55,414] {bash.py:177} INFO - Command exited with return code 0
[2021-01-21 23:22:55,435] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=trigger_rule, task_id=task_3, execution_date=20210121T232253, start_date=20210121T232255, end_date=20210121T232255
[2021-01-21 23:22:55,463] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-01-21 23:22:55,470] {local_task_job.py:118} INFO - Task exited with return code 0
