[2021-01-22 21:21:19,225] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.connection_to_es 2021-01-22T21:21:16.847743+00:00 [queued]>
[2021-01-22 21:21:19,241] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.connection_to_es 2021-01-22T21:21:16.847743+00:00 [queued]>
[2021-01-22 21:21:19,241] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-22 21:21:19,241] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-22 21:21:19,241] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-22 21:21:19,248] {taskinstance.py:1038} INFO - Executing <Task(PostgresToElasticOperator): connection_to_es> on 2021-01-22T21:21:16.847743+00:00
[2021-01-22 21:21:19,251] {standard_task_runner.py:51} INFO - Started process 871292 to run task
[2021-01-22 21:21:19,256] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'elasticsearch_dag', 'connection_to_es', '2021-01-22T21:21:16.847743+00:00', '--job-id', '149', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/elasticsearch_dag.py', '--cfg-path', '/tmp/tmp6nvlhmh5']
[2021-01-22 21:21:19,257] {standard_task_runner.py:76} INFO - Job 149: Subtask connection_to_es
[2021-01-22 21:21:19,306] {logging_mixin.py:103} INFO - Running <TaskInstance: elasticsearch_dag.connection_to_es 2021-01-22T21:21:16.847743+00:00 [running]> on host ip-172-31-18-6.ap-south-1.compute.internal
[2021-01-22 21:21:19,352] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=elasticsearch_dag
AIRFLOW_CTX_TASK_ID=connection_to_es
AIRFLOW_CTX_EXECUTION_DATE=2021-01-22T21:21:16.847743+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-01-22T21:21:16.847743+00:00
[2021-01-22 21:21:19,364] {base.py:74} INFO - Using connection to: id: elasticsearch_default. Host: localhost, Port: 9200, Schema: http, Login: None, Password: None, extra: None
[2021-01-22 21:21:19,376] {base.py:74} INFO - Using connection to: id: postgres_default. Host: localhost, Port: 5432, Schema: , Login: postgres, Password: XXXXXXXX, extra: XXXXXXXX
[2021-01-22 21:21:19,385] {taskinstance.py:1396} ERROR - name 'sql' is not defined
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/airflow_udemy/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ubuntu/anaconda3/envs/airflow_udemy/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ubuntu/anaconda3/envs/airflow_udemy/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ubuntu/airflow/plugins/elasticsearch_plugin/operators/postgres_to_elastic.py", line 26, in execute
    cur.execute(sql)
NameError: name 'sql' is not defined
[2021-01-22 21:21:19,387] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=elasticsearch_dag, task_id=connection_to_es, execution_date=20210122T212116, start_date=20210122T212119, end_date=20210122T212119
[2021-01-22 21:21:19,427] {local_task_job.py:118} INFO - Task exited with return code 1
